baseurl = "https://www.ymotongpoo.com/works/goblog-ja/"
languageCode = "ja-jp"
title = "The Go Blog 日本語訳"
pagenate = 20
description = "The Go Blogの日本語訳を公開しています。修正は https://github.com/ymotongpoo/goblog-ja/ まで。"
copyright = "Except as noted, the content of this page is licensed under the Creative Commons Attribution 3.0 License, and code is licensed under a BSD license. The Go team (original) and Yoshi Yamaguchi (translation)" 

[Params]
twitter = "ymotongpoo"
github = "ymotongpoo"
ga = "UA-6420772-8"
