baseurl = "https://www.ymotongpoo.com/works/goblog-ja/"
languageCode = "ja-jp"
title = "The Go Blog 日本語訳"
paginate = 200

[Params]
copyright = "Except as noted, the content of this page is licensed under the Creative Commons Attribution 3.0 License, and code is licensed under a BSD license. The Go team (original) and Yoshi Yamaguchi (translation)" 
github = "https://github.com/ymotongpoo/goblog-ja/"
analytics = "UA-6420772-8"
